### PR TITLE
[CNXC-359] Classify covidnet ui feeds in their names

### PR DESCRIPTION
**Pull request by mslwang**
(I made a PR with the wrong ticket name in the title, so I created another branch to PR for the correct ticket)
In a production setting with many different UIs, there's a chance that not all feeds will belong to the covidnet UI. In our dev environment, we currently don't do anything to distinguish them.

Before
beforeName

After
afterName

Chris UI
chris_ui-Names

### CODE REVIEW

**Comment by mslwang** [comment]
Remember to rebase

**Review by micklynch — CHANGES_REQUESTED** [review]
Please rebase this branch from development

**Review by micklynch — CHANGES_REQUESTED** [review]
Please rebase ....

**Comment by mslwang** [comment]
Opened updated PR on #83.

**Pull request closed without merging**
